version: '3.3'
services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      debank_net:
        ipv4_address: 176.23.0.2

networks:
  debank_net:
    ipam:
      driver: default
      config:
        - subnet: 176.23.0.0/16
